export const SKILL_TAXONOMY: Record<string, string[]> = {
  programming: [
    'python',
    'javascript',
    'typescript',
    'java',
    'c#',
    'c++',
    'go',
    'golang',
    'rust',
    'ruby',
    'php',
    'swift',
    'kotlin',
    'scala',
    'dart',
    'bash',
    'powershell',
    'shell scripting',
    'html',
    'css',
    'sass',
    'graphql',
    'objective-c',
  ],
  frameworks: [
    'react',
    'react native',
    'angular',
    'vue',
    'svelte',
    'next.js',
    'nuxt.js',
    'node.js',
    'nodejs',
    'express',
    'nestjs',
    'django',
    'flask',
    'fastapi',
    'spring boot',
    '.net',
    'asp.net',
    'laravel',
    'ruby on rails',
    'flutter',
    'tailwind',
    'tailwind css',
    'bootstrap',
    'material ui',
    'redux',
    'webpack',
    'vite',
    'pytest',
    'jest',
    'vitest',
    'cypress',
    'playwright',
  ],
  data: [
    'sql',
    'postgresql',
    'mysql',
    'sql server',
    'mongodb',
    'redis',
    'elasticsearch',
    'snowflake',
    'bigquery',
    'redshift',
    'databricks',
    'apache spark',
    'kafka',
    'airflow',
    'dbt',
    'etl',
    'data analysis',
    'data analytics',
    'data science',
    'machine learning',
    'deep learning',
    'natural language processing',
    'nlp',
    'computer vision',
    'pandas',
    'numpy',
    'scikit-learn',
    'tensorflow',
    'pytorch',
    'power bi',
    'tableau',
    'excel',
    'google sheets',
    'data visualization',
    'statistics',
    'statistical analysis',
    'a/b testing',
    'forecasting',
    'data modeling',
  ],
  cloud_devops: [
    'aws',
    'azure',
    'gcp',
    'google cloud',
    'docker',
    'kubernetes',
    'terraform',
    'ansible',
    'jenkins',
    'github actions',
    'gitlab ci',
    'ci/cd',
    'devops',
    'site reliability engineering',
    'sre',
    'linux',
    'nginx',
    'apache',
    'serverless',
    'lambda',
    'cloudflare',
    'vercel',
    'netlify',
    'firebase',
    'supabase',
    'edge functions',
    'monitoring',
    'observability',
    'prometheus',
    'grafana',
    'datadog',
    'sentry',
    'logging',
    'infrastructure as code',
    'helm',
    'containerization',
  ],
  security: [
    'cybersecurity',
    'information security',
    'network security',
    'application security',
    'security auditing',
    'penetration testing',
    'vulnerability assessment',
    'threat modeling',
    'identity and access management',
    'iam',
    'oauth',
    'openid connect',
    'jwt',
    'encryption',
    'cryptography',
    'ssl',
    'tls',
    'owasp',
    'secure coding',
    'incident response',
    'risk assessment',
    'compliance',
    'gdpr',
    'hipaa',
    'soc 2',
    'iso 27001',
    'zero trust',
    'firewall',
    'siem',
  ],
  product_project: [
    'project management',
    'program management',
    'product management',
    'product strategy',
    'roadmapping',
    'requirements gathering',
    'business analysis',
    'stakeholder management',
    'agile',
    'scrum',
    'kanban',
    'sprint planning',
    'backlog management',
    'user stories',
    'acceptance criteria',
    'delivery management',
    'change management',
    'risk management',
    'resource planning',
    'budget management',
    'vendor management',
    'process improvement',
    'lean',
    'six sigma',
    'okr',
    'kpi',
    'go-to-market',
    'market research',
    'competitive analysis',
  ],
  design: [
    'figma',
    'sketch',
    'adobe xd',
    'photoshop',
    'illustrator',
    'indesign',
    'ui/ux',
    'ux design',
    'ui design',
    'user research',
    'usability testing',
    'wireframing',
    'prototyping',
    'design systems',
    'interaction design',
    'information architecture',
    'accessibility',
    'wcag',
    'responsive design',
    'mobile design',
    'visual design',
    'brand design',
    'journey mapping',
    'service design',
    'design thinking',
  ],
  marketing_sales: [
    'seo',
    'sem',
    'paid search',
    'paid social',
    'content marketing',
    'email marketing',
    'social media',
    'google analytics',
    'ga4',
    'hubspot',
    'salesforce',
    'crm',
    'copywriting',
    'conversion optimization',
    'cro',
    'lead generation',
    'demand generation',
    'account management',
    'business development',
    'sales strategy',
    'customer success',
    'customer support',
    'market segmentation',
    'brand strategy',
    'public relations',
    'event marketing',
    'marketing automation',
    'community management',
  ],
  finance_operations: [
    'financial analysis',
    'financial modeling',
    'budgeting',
    'forecasting',
    'accounting',
    'bookkeeping',
    'accounts payable',
    'accounts receivable',
    'payroll',
    'auditing',
    'tax',
    'variance analysis',
    'investment analysis',
    'portfolio management',
    'risk analysis',
    'procurement',
    'supply chain',
    'inventory management',
    'operations management',
    'logistics',
    'process mapping',
    'quality assurance',
    'quality control',
    'erp',
    'sap',
    'quickbooks',
    'xero',
  ],
  general_soft_skills: [
    'microsoft office',
    'communication',
    'written communication',
    'verbal communication',
    'presentation',
    'public speaking',
    'team leadership',
    'people management',
    'mentoring',
    'coaching',
    'collaboration',
    'problem solving',
    'critical thinking',
    'analytical thinking',
    'decision making',
    'strategic planning',
    'time management',
    'organization',
    'adaptability',
    'customer service',
    'negotiation',
    'conflict resolution',
    'training',
    'documentation',
    'technical writing',
    'research',
    'reporting',
    'remote collaboration',
    'cross-functional collaboration',
    'attention to detail',
  ],
};

export const FLAT_TAXONOMY: string[] = Array.from(new Set(Object.values(SKILL_TAXONOMY).flat()));
