CREATE TABLE resumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    file_name TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE resumes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to manage their own resumes"
ON resumes
FOR ALL
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);
